# Generated by Django 4.2.5 on 2024-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascent', '0003_alter_newuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
