# Generated by Django 4.2.5 on 2024-04-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascent', '0004_alter_newuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='address',
            new_name='cardno',
        ),
    ]
