# Generated by Django 4.2.5 on 2024-04-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascent', '0005_rename_address_newuser_cardno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
    ]
