# Generated by Django 4.2.5 on 2024-04-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascent', '0007_alter_newuser_cardno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
